<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE biblioteca[
    <!--Elemento biblioteca-->
    <!ELEMENT biblioteca (libro*, revista*, periodico*)>
    
    <!-- Libro y sus atributos -->
    <!ELEMENT libro (titulo, capitulo+, indice, sinopsis)>
    <!ATTLIST libro id ID #REQUIRED>
    <!ATTLIST libro tipo_clase (novela | infantil |didactico) #REQUIRED>
    <!ATTLIST libro numero_paginas CDATA #REQUIRED>

    <!-- Revista y sus atributos -->
    <!ELEMENT revista (titulo, numero, indice, seccion_revista+)>
    <!ATTLIST revista id ID #REQUIRED>
    <!ATTLIST revista tipo_clase (informatica|corazon|coches|investigacion|otra) #REQUIRED>
    <!ATTLIST revista numero_paginas CDATA #REQUIRED>

    <!-- Periódico y sus atributos -->
    <!ELEMENT periodico (seccion_periodico+, indice)>
    <!ATTLIST periodico id ID #REQUIRED>
    <!ATTLIST periodico tipo_clase (nacional|internacional) #REQUIRED>
    <!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>

    
    <!-- Elementos comunes -->
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT indice (#PCDATA)>


    <!-- Elementos de libro -->
    <!ELEMENT capitulo (titulo_capitulo,contenido)>
    <!ATTLIST capitulo numero_paginas CDATA #REQUIRED>
    <!ELEMENT sinopsis (#PCDATA)>
    <!ELEMENT titulo_capitulo (#PCDATA)>


    <!-- Elementos de revista -->
    <!ELEMENT numero (#PCDATA)>
    <!ELEMENT seccion_revista (contenido)>
    <!ATTLIST seccion_revista numero_paginas CDATA #REQUIRED>


    <!-- Elementos de periódico -->
    <!ELEMENT seccion_periodico (articulo+)>
    <!ATTLIST seccion_periodico tipo_seccion (economica|opinion|deportes|nacional|internacional) #REQUIRED>
    <!ELEMENT articulo (contenido)>
    <!ATTLIST articulo autor CDATA #REQUIRED>

    <!-- Contenido -->
    <!ELEMENT contenido (#PCDATA)>
    <!ATTLIST contenido enlace CDATA #REQUIRED>

]>

<biblioteca>
    <libro id="L0001" tipo_clase="novela" numero_paginas="350">
        <titulo> El pajaro carpintero</titulo>
        <capitulo numero_paginas="10">
           <titulo_capitulo>El comienzo</titulo_capitulo>
           <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">Aqui va un contenido o vacio, hay que preguntarlo</contenido>
        </capitulo>
        <capitulo numero_paginas="20">
           <titulo_capitulo>El segundo</titulo_capitulo>
           <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">Aqui va un contenido o vacio, hay que preguntarlo</contenido>
        </capitulo>
        <indice>
           1- El comienzo   pagina 4 
           2- El segundo    pagina 11
        </indice>
        <sinopsis>
           El libro trata sobre la exclavitud en América</sinopsis>
     </libro>

     <revista id="R0001" tipo_clase="investigacion" numero_paginas="21">
        <titulo>Ciencia e investigacion</titulo>
        <numero>1</numero>
        <indice> 
           1- Primera seccion   pagina 1 
           2- Segunda seccion    pagina 11
        </indice>
        <seccion_revista numero_paginas="10">
           <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">Es el contenido de la primera seccion</contenido>
        </seccion_revista> 
        <seccion_revista numero_paginas="11">
           <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">Es el contenido de la segunda seccion</contenido>
        </seccion_revista>
     </revista>

     <periodico id="P0001" tipo_clase="nacional" fecha_publicacion="01/05/2021">
        <seccion_periodico tipo_seccion="nacional">
           <articulo autor="Ana Perez">
               <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">Articulo sobre las elecciones de Madrid</contenido>
           </articulo>
           <articulo autor="Ana Perez">
               <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">El ERTE durante la Pandemia</contenido>
           </articulo>
        </seccion_periodico>
        <seccion_periodico tipo_seccion="internacional">
           <articulo autor="Antonio Jose Mistral">
              <contenido enlace="https://www.w3schools.com/xml/xml_dtd_attributes.asp">Articulo sobre la liberalizacion de las patentes</contenido>
           </articulo>
        </seccion_periodico>
        <indice>
           1- Elecciones Madrid   pagina 1 
           2- Liberalizacion patentes    pagina 4
        </indice>
     </periodico>
</biblioteca>